//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


using System;
using System.Runtime.InteropServices;

namespace Noesis
{

public class DependencyPropertyChangedEventArgs : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DependencyPropertyChangedEventArgs(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(DependencyPropertyChangedEventArgs obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~DependencyPropertyChangedEventArgs() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NoesisGUI_PINVOKE.delete_DependencyPropertyChangedEventArgs(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public object NewValue {
    get {
      return GetNewValueHelper();
    }
  }
  
  public object OldValue {
    get {
      return GetOldValueHelper();
    }
  }
  
  public Noesis.DependencyProperty Property {
    get {
      return GetPropertyHelper();
    }
  }

  public DependencyPropertyChangedEventArgs(DependencyProperty dp, IntPtr ov, IntPtr nv) : this(NoesisGUI_PINVOKE.new_DependencyPropertyChangedEventArgs(DependencyProperty.getCPtr(dp), ov, nv), true) {
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
  }

  private object GetNewValueHelper() {
    IntPtr cPtr = NoesisGUI_PINVOKE.DependencyPropertyChangedEventArgs_GetNewValueHelper(swigCPtr);
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    return Noesis.Extend.GetProxy(cPtr, false);
  }

  private object GetOldValueHelper() {
    IntPtr cPtr = NoesisGUI_PINVOKE.DependencyPropertyChangedEventArgs_GetOldValueHelper(swigCPtr);
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    return Noesis.Extend.GetProxy(cPtr, false);
  }

  private DependencyProperty GetPropertyHelper() {
    IntPtr cPtr = NoesisGUI_PINVOKE.DependencyPropertyChangedEventArgs_GetPropertyHelper(swigCPtr);
    if (NoesisGUI_PINVOKE.SWIGPendingException.Pending) throw NoesisGUI_PINVOKE.SWIGPendingException.Retrieve();
    return (DependencyProperty)Noesis.Extend.GetProxy(cPtr, false);
  }

}

}

